before:
  hooks:
    # You may remove this if you don't use go modules.
    # - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: nfpm-default
    package_name: moonlogs
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Mark Cholak
    homepage: https://github.com/pijng/moonlogs/
    maintainer: Mark Cholak <shalpack@gmail.com>
    description: Business event-logging tool with a built-in user-friendly web interface for easy access to events.
    license: Apache-2.0
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - nfpm-default
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/pijng/

dockers:
  - image_templates:
      - "pijng/moonlogs:{{ .Tag }}"
      - "pijng/moonlogs:v{{ .Major }}"
      - "pijng/moonlogs:v{{ .Major }}.{{ .Minor }}"
      - "pijng/moonlogs:latest"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    skip_push: false