// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"moonlogs/ent/logrecord"
	"moonlogs/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogRecordDelete is the builder for deleting a LogRecord entity.
type LogRecordDelete struct {
	config
	hooks    []Hook
	mutation *LogRecordMutation
}

// Where appends a list predicates to the LogRecordDelete builder.
func (lrd *LogRecordDelete) Where(ps ...predicate.LogRecord) *LogRecordDelete {
	lrd.mutation.Where(ps...)
	return lrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lrd *LogRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lrd.sqlExec, lrd.mutation, lrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lrd *LogRecordDelete) ExecX(ctx context.Context) int {
	n, err := lrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lrd *LogRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(logrecord.Table, sqlgraph.NewFieldSpec(logrecord.FieldID, field.TypeInt))
	if ps := lrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lrd.mutation.done = true
	return affected, err
}

// LogRecordDeleteOne is the builder for deleting a single LogRecord entity.
type LogRecordDeleteOne struct {
	lrd *LogRecordDelete
}

// Where appends a list predicates to the LogRecordDelete builder.
func (lrdo *LogRecordDeleteOne) Where(ps ...predicate.LogRecord) *LogRecordDeleteOne {
	lrdo.lrd.mutation.Where(ps...)
	return lrdo
}

// Exec executes the deletion query.
func (lrdo *LogRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := lrdo.lrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{logrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lrdo *LogRecordDeleteOne) ExecX(ctx context.Context) {
	if err := lrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
