// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moonlogs/ent/logrecord"
	"moonlogs/ent/predicate"
	"moonlogs/ent/schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogRecordUpdate is the builder for updating LogRecord entities.
type LogRecordUpdate struct {
	config
	hooks    []Hook
	mutation *LogRecordMutation
}

// Where appends a list predicates to the LogRecordUpdate builder.
func (lru *LogRecordUpdate) Where(ps ...predicate.LogRecord) *LogRecordUpdate {
	lru.mutation.Where(ps...)
	return lru
}

// SetQuery sets the "query" field.
func (lru *LogRecordUpdate) SetQuery(s schema.Query) *LogRecordUpdate {
	lru.mutation.SetQuery(s)
	return lru
}

// Mutation returns the LogRecordMutation object of the builder.
func (lru *LogRecordUpdate) Mutation() *LogRecordMutation {
	return lru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lru *LogRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lru.sqlSave, lru.mutation, lru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lru *LogRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := lru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lru *LogRecordUpdate) Exec(ctx context.Context) error {
	_, err := lru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lru *LogRecordUpdate) ExecX(ctx context.Context) {
	if err := lru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lru *LogRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(logrecord.Table, logrecord.Columns, sqlgraph.NewFieldSpec(logrecord.FieldID, field.TypeInt))
	if ps := lru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lru.mutation.Query(); ok {
		_spec.SetField(logrecord.FieldQuery, field.TypeJSON, value)
	}
	if lru.mutation.GroupHashCleared() {
		_spec.ClearField(logrecord.FieldGroupHash, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lru.mutation.done = true
	return n, nil
}

// LogRecordUpdateOne is the builder for updating a single LogRecord entity.
type LogRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LogRecordMutation
}

// SetQuery sets the "query" field.
func (lruo *LogRecordUpdateOne) SetQuery(s schema.Query) *LogRecordUpdateOne {
	lruo.mutation.SetQuery(s)
	return lruo
}

// Mutation returns the LogRecordMutation object of the builder.
func (lruo *LogRecordUpdateOne) Mutation() *LogRecordMutation {
	return lruo.mutation
}

// Where appends a list predicates to the LogRecordUpdate builder.
func (lruo *LogRecordUpdateOne) Where(ps ...predicate.LogRecord) *LogRecordUpdateOne {
	lruo.mutation.Where(ps...)
	return lruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lruo *LogRecordUpdateOne) Select(field string, fields ...string) *LogRecordUpdateOne {
	lruo.fields = append([]string{field}, fields...)
	return lruo
}

// Save executes the query and returns the updated LogRecord entity.
func (lruo *LogRecordUpdateOne) Save(ctx context.Context) (*LogRecord, error) {
	return withHooks(ctx, lruo.sqlSave, lruo.mutation, lruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lruo *LogRecordUpdateOne) SaveX(ctx context.Context) *LogRecord {
	node, err := lruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lruo *LogRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := lruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lruo *LogRecordUpdateOne) ExecX(ctx context.Context) {
	if err := lruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lruo *LogRecordUpdateOne) sqlSave(ctx context.Context) (_node *LogRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(logrecord.Table, logrecord.Columns, sqlgraph.NewFieldSpec(logrecord.FieldID, field.TypeInt))
	id, ok := lruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LogRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logrecord.FieldID)
		for _, f := range fields {
			if !logrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != logrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lruo.mutation.Query(); ok {
		_spec.SetField(logrecord.FieldQuery, field.TypeJSON, value)
	}
	if lruo.mutation.GroupHashCleared() {
		_spec.ClearField(logrecord.FieldGroupHash, field.TypeString)
	}
	_node = &LogRecord{config: lruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lruo.mutation.done = true
	return _node, nil
}
