// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"moonlogs/ent/logschema"
	"moonlogs/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogSchemaDelete is the builder for deleting a LogSchema entity.
type LogSchemaDelete struct {
	config
	hooks    []Hook
	mutation *LogSchemaMutation
}

// Where appends a list predicates to the LogSchemaDelete builder.
func (lsd *LogSchemaDelete) Where(ps ...predicate.LogSchema) *LogSchemaDelete {
	lsd.mutation.Where(ps...)
	return lsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lsd *LogSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lsd.sqlExec, lsd.mutation, lsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lsd *LogSchemaDelete) ExecX(ctx context.Context) int {
	n, err := lsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lsd *LogSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(logschema.Table, sqlgraph.NewFieldSpec(logschema.FieldID, field.TypeInt))
	if ps := lsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lsd.mutation.done = true
	return affected, err
}

// LogSchemaDeleteOne is the builder for deleting a single LogSchema entity.
type LogSchemaDeleteOne struct {
	lsd *LogSchemaDelete
}

// Where appends a list predicates to the LogSchemaDelete builder.
func (lsdo *LogSchemaDeleteOne) Where(ps ...predicate.LogSchema) *LogSchemaDeleteOne {
	lsdo.lsd.mutation.Where(ps...)
	return lsdo
}

// Exec executes the deletion query.
func (lsdo *LogSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := lsdo.lsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{logschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lsdo *LogSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := lsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
