// Code generated by ent, DO NOT EDIT.

package logschema

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the logschema type in the database.
	Label = "log_schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFields holds the string denoting the fields field in the database.
	FieldFields = "fields"
	// FieldRetentionTime holds the string denoting the retention_time field in the database.
	FieldRetentionTime = "retention_time"
	// Table holds the table name of the logschema in the database.
	Table = "log_schemas"
)

// Columns holds all SQL columns for logschema fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldName,
	FieldFields,
	FieldRetentionTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the LogSchema queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRetentionTime orders the results by the retention_time field.
func ByRetentionTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetentionTime, opts...).ToFunc()
}
