// Code generated by ent, DO NOT EDIT.

package logschema

import (
	"moonlogs/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldDescription, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldName, v))
}

// RetentionTime applies equality check predicate on the "retention_time" field. It's identical to RetentionTimeEQ.
func RetentionTime(v int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldRetentionTime, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldContainsFold(FieldDescription, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldContainsFold(FieldName, v))
}

// RetentionTimeEQ applies the EQ predicate on the "retention_time" field.
func RetentionTimeEQ(v int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldEQ(FieldRetentionTime, v))
}

// RetentionTimeNEQ applies the NEQ predicate on the "retention_time" field.
func RetentionTimeNEQ(v int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNEQ(FieldRetentionTime, v))
}

// RetentionTimeIn applies the In predicate on the "retention_time" field.
func RetentionTimeIn(vs ...int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldIn(FieldRetentionTime, vs...))
}

// RetentionTimeNotIn applies the NotIn predicate on the "retention_time" field.
func RetentionTimeNotIn(vs ...int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNotIn(FieldRetentionTime, vs...))
}

// RetentionTimeGT applies the GT predicate on the "retention_time" field.
func RetentionTimeGT(v int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGT(FieldRetentionTime, v))
}

// RetentionTimeGTE applies the GTE predicate on the "retention_time" field.
func RetentionTimeGTE(v int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldGTE(FieldRetentionTime, v))
}

// RetentionTimeLT applies the LT predicate on the "retention_time" field.
func RetentionTimeLT(v int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLT(FieldRetentionTime, v))
}

// RetentionTimeLTE applies the LTE predicate on the "retention_time" field.
func RetentionTimeLTE(v int64) predicate.LogSchema {
	return predicate.LogSchema(sql.FieldLTE(FieldRetentionTime, v))
}

// RetentionTimeIsNil applies the IsNil predicate on the "retention_time" field.
func RetentionTimeIsNil() predicate.LogSchema {
	return predicate.LogSchema(sql.FieldIsNull(FieldRetentionTime))
}

// RetentionTimeNotNil applies the NotNil predicate on the "retention_time" field.
func RetentionTimeNotNil() predicate.LogSchema {
	return predicate.LogSchema(sql.FieldNotNull(FieldRetentionTime))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LogSchema) predicate.LogSchema {
	return predicate.LogSchema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LogSchema) predicate.LogSchema {
	return predicate.LogSchema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LogSchema) predicate.LogSchema {
	return predicate.LogSchema(sql.NotPredicates(p))
}
