// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	Http1Scopes = "http1.Scopes"
)

// Defines values for LogLevel.
const (
	Debug LogLevel = "Debug"
	Error LogLevel = "Error"
	Fatal LogLevel = "Fatal"
	Info  LogLevel = "Info"
	Trace LogLevel = "Trace"
	Warn  LogLevel = "Warn"
)

// Defines values for UserRole.
const (
	Admin  UserRole = "Admin"
	Member UserRole = "Member"
	System UserRole = "System"
)

// Credentials defines model for Credentials.
type Credentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LogLevel defines model for LogLevel.
type LogLevel string

// LogRecord defines model for LogRecord.
type LogRecord struct {
	CreatedAt  *string                `json:"created_at,omitempty"`
	GroupHash  *string                `json:"group_hash,omitempty"`
	Id         int                    `json:"id"`
	Level      *LogRecord_Level       `json:"level,omitempty"`
	Query      map[string]interface{} `json:"query"`
	SchemaId   *int                   `json:"schema_id,omitempty"`
	SchemaName string                 `json:"schema_name"`
	Text       string                 `json:"text"`
}

// LogRecord_Level defines model for LogRecord.Level.
type LogRecord_Level struct {
	union json.RawMessage
}

// LogSchema defines model for LogSchema.
type LogSchema struct {
	Description   *string       `json:"description,omitempty"`
	Fields        []SchemaField `json:"fields"`
	Id            int           `json:"id"`
	Name          string        `json:"name"`
	RetentionTime *int          `json:"retention_time,omitempty"`
	Title         string        `json:"title"`
}

// LogSchemaSearch defines model for LogSchemaSearch.
type LogSchemaSearch struct {
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// Meta defines model for Meta.
type Meta struct {
	Count int `json:"count"`
	Page  int `json:"page"`
	Pages int `json:"pages"`
}

// SchemaField defines model for SchemaField.
type SchemaField struct {
	Name  string `json:"name"`
	Title string `json:"title"`
}

// Session defines model for Session.
type Session struct {
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	Email          string    `json:"email"`
	Id             int       `json:"id"`
	Name           string    `json:"name"`
	Password       string    `json:"password"`
	PasswordDigest *string   `json:"password_digest,omitempty"`
	Role           User_Role `json:"role"`
	Token          *string   `json:"token,omitempty"`
}

// User_Role defines model for User.Role.
type User_Role struct {
	union json.RawMessage
}

// UserRole defines model for UserRole.
type UserRole string

// PostApiLogsSearchParams defines parameters for PostApiLogsSearch.
type PostApiLogsSearchParams struct {
	Page  *string `form:"page,omitempty" json:"page,omitempty"`
	Limit *string `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostApiLogsJSONRequestBody defines body for PostApiLogs for application/json ContentType.
type PostApiLogsJSONRequestBody = LogRecord

// PostApiLogsSearchJSONRequestBody defines body for PostApiLogsSearch for application/json ContentType.
type PostApiLogsSearchJSONRequestBody = LogRecord

// PostApiSchemasJSONRequestBody defines body for PostApiSchemas for application/json ContentType.
type PostApiSchemasJSONRequestBody = LogSchema

// PostApiSchemasSearchJSONRequestBody defines body for PostApiSchemasSearch for application/json ContentType.
type PostApiSchemasSearchJSONRequestBody = LogSchemaSearch

// PutApiSchemasIdJSONRequestBody defines body for PutApiSchemasId for application/json ContentType.
type PutApiSchemasIdJSONRequestBody = LogSchema

// PostApiSessionJSONRequestBody defines body for PostApiSession for application/json ContentType.
type PostApiSessionJSONRequestBody = Credentials

// PostApiUsersJSONRequestBody defines body for PostApiUsers for application/json ContentType.
type PostApiUsersJSONRequestBody = User

// PutApiUsersIdJSONRequestBody defines body for PutApiUsersId for application/json ContentType.
type PutApiUsersIdJSONRequestBody = User

// AsLogLevel returns the union data inside the LogRecord_Level as a LogLevel
func (t LogRecord_Level) AsLogLevel() (LogLevel, error) {
	var body LogLevel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLogLevel overwrites any union data inside the LogRecord_Level as the provided LogLevel
func (t *LogRecord_Level) FromLogLevel(v LogLevel) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLogLevel performs a merge with any union data inside the LogRecord_Level, using the provided LogLevel
func (t *LogRecord_Level) MergeLogLevel(v LogLevel) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t LogRecord_Level) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LogRecord_Level) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUserRole returns the union data inside the User_Role as a UserRole
func (t User_Role) AsUserRole() (UserRole, error) {
	var body UserRole
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserRole overwrites any union data inside the User_Role as the provided UserRole
func (t *User_Role) FromUserRole(v UserRole) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserRole performs a merge with any union data inside the User_Role, using the provided UserRole
func (t *User_Role) MergeUserRole(v UserRole) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t User_Role) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *User_Role) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/logs)
	GetApiLogs(w http.ResponseWriter, r *http.Request)

	// (POST /api/logs)
	PostApiLogs(w http.ResponseWriter, r *http.Request)

	// (GET /api/logs/group/{schema_name}/{hash})
	GetApiLogsGroupSchemaNameHash(w http.ResponseWriter, r *http.Request, schemaName string, hash string)

	// (POST /api/logs/search)
	PostApiLogsSearch(w http.ResponseWriter, r *http.Request, params PostApiLogsSearchParams)

	// (GET /api/logs/{id})
	GetApiLogsId(w http.ResponseWriter, r *http.Request, id string)

	// (GET /api/schemas)
	GetApiSchemas(w http.ResponseWriter, r *http.Request)

	// (POST /api/schemas)
	PostApiSchemas(w http.ResponseWriter, r *http.Request)

	// (POST /api/schemas/search)
	PostApiSchemasSearch(w http.ResponseWriter, r *http.Request)

	// (GET /api/schemas/{id})
	GetApiSchemasId(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /api/schemas/{id})
	PutApiSchemasId(w http.ResponseWriter, r *http.Request, id string)

	// (GET /api/session)
	GetApiSession(w http.ResponseWriter, r *http.Request)

	// (POST /api/session)
	PostApiSession(w http.ResponseWriter, r *http.Request)

	// (GET /api/users)
	GetApiUsers(w http.ResponseWriter, r *http.Request)

	// (POST /api/users)
	PostApiUsers(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/users/{id})
	DeleteApiUsersId(w http.ResponseWriter, r *http.Request, id string)

	// (GET /api/users/{id})
	GetApiUsersId(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /api/users/{id})
	PutApiUsersId(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiLogs operation middleware
func (siw *ServerInterfaceWrapper) GetApiLogs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLogs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiLogs operation middleware
func (siw *ServerInterfaceWrapper) PostApiLogs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLogs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiLogsGroupSchemaNameHash operation middleware
func (siw *ServerInterfaceWrapper) GetApiLogsGroupSchemaNameHash(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "schema_name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema_name", mux.Vars(r)["schema_name"], &schemaName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schema_name", Err: err})
		return
	}

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameter("simple", false, "hash", mux.Vars(r)["hash"], &hash)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLogsGroupSchemaNameHash(w, r, schemaName, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiLogsSearch operation middleware
func (siw *ServerInterfaceWrapper) PostApiLogsSearch(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiLogsSearchParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLogsSearch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiLogsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiLogsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLogsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiSchemas operation middleware
func (siw *ServerInterfaceWrapper) GetApiSchemas(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiSchemas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiSchemas operation middleware
func (siw *ServerInterfaceWrapper) PostApiSchemas(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiSchemas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiSchemasSearch operation middleware
func (siw *ServerInterfaceWrapper) PostApiSchemasSearch(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiSchemasSearch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiSchemasId operation middleware
func (siw *ServerInterfaceWrapper) GetApiSchemasId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiSchemasId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutApiSchemasId operation middleware
func (siw *ServerInterfaceWrapper) PutApiSchemasId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiSchemasId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiSession operation middleware
func (siw *ServerInterfaceWrapper) GetApiSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiSession operation middleware
func (siw *ServerInterfaceWrapper) PostApiSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiUsers operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiUsers operation middleware
func (siw *ServerInterfaceWrapper) PostApiUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteApiUsersId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiUsersId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiUsersId operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutApiUsersId operation middleware
func (siw *ServerInterfaceWrapper) PutApiUsersId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, Http1Scopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/api/logs", wrapper.GetApiLogs).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/logs", wrapper.PostApiLogs).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/logs/group/{schema_name}/{hash}", wrapper.GetApiLogsGroupSchemaNameHash).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/logs/search", wrapper.PostApiLogsSearch).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/logs/{id}", wrapper.GetApiLogsId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/schemas", wrapper.GetApiSchemas).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/schemas", wrapper.PostApiSchemas).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/schemas/search", wrapper.PostApiSchemasSearch).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/schemas/{id}", wrapper.GetApiSchemasId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/schemas/{id}", wrapper.PutApiSchemasId).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/api/session", wrapper.GetApiSession).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/session", wrapper.PostApiSession).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/users", wrapper.GetApiUsers).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/users", wrapper.PostApiUsers).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/users/{id}", wrapper.DeleteApiUsersId).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/api/users/{id}", wrapper.GetApiUsersId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/users/{id}", wrapper.PutApiUsersId).Methods("PUT")

	return r
}

type GetApiLogsRequestObject struct {
}

type GetApiLogsResponseObject interface {
	VisitGetApiLogsResponse(w http.ResponseWriter) error
}

type GetApiLogs200JSONResponse struct {
	Code    int         `json:"code"`
	Data    []LogRecord `json:"data"`
	Error   string      `json:"error"`
	Meta    Meta        `json:"meta"`
	Success bool        `json:"success"`
}

func (response GetApiLogs200JSONResponse) VisitGetApiLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLogsRequestObject struct {
	Body *PostApiLogsJSONRequestBody
}

type PostApiLogsResponseObject interface {
	VisitPostApiLogsResponse(w http.ResponseWriter) error
}

type PostApiLogs200JSONResponse struct {
	Code    int       `json:"code"`
	Data    LogRecord `json:"data"`
	Error   string    `json:"error"`
	Meta    Meta      `json:"meta"`
	Success bool      `json:"success"`
}

func (response PostApiLogs200JSONResponse) VisitPostApiLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiLogsGroupSchemaNameHashRequestObject struct {
	SchemaName string `json:"schema_name"`
	Hash       string `json:"hash"`
}

type GetApiLogsGroupSchemaNameHashResponseObject interface {
	VisitGetApiLogsGroupSchemaNameHashResponse(w http.ResponseWriter) error
}

type GetApiLogsGroupSchemaNameHash200JSONResponse struct {
	Code    int         `json:"code"`
	Data    []LogRecord `json:"data"`
	Error   string      `json:"error"`
	Meta    Meta        `json:"meta"`
	Success bool        `json:"success"`
}

func (response GetApiLogsGroupSchemaNameHash200JSONResponse) VisitGetApiLogsGroupSchemaNameHashResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLogsSearchRequestObject struct {
	Params PostApiLogsSearchParams
	Body   *PostApiLogsSearchJSONRequestBody
}

type PostApiLogsSearchResponseObject interface {
	VisitPostApiLogsSearchResponse(w http.ResponseWriter) error
}

type PostApiLogsSearch200JSONResponse struct {
	Code    int         `json:"code"`
	Data    []LogRecord `json:"data"`
	Error   string      `json:"error"`
	Meta    Meta        `json:"meta"`
	Success bool        `json:"success"`
}

func (response PostApiLogsSearch200JSONResponse) VisitPostApiLogsSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiLogsIdRequestObject struct {
	Id string `json:"id"`
}

type GetApiLogsIdResponseObject interface {
	VisitGetApiLogsIdResponse(w http.ResponseWriter) error
}

type GetApiLogsId200JSONResponse struct {
	Code    int       `json:"code"`
	Data    LogRecord `json:"data"`
	Error   string    `json:"error"`
	Meta    Meta      `json:"meta"`
	Success bool      `json:"success"`
}

func (response GetApiLogsId200JSONResponse) VisitGetApiLogsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiSchemasRequestObject struct {
}

type GetApiSchemasResponseObject interface {
	VisitGetApiSchemasResponse(w http.ResponseWriter) error
}

type GetApiSchemas200JSONResponse struct {
	Code    int         `json:"code"`
	Data    []LogSchema `json:"data"`
	Error   string      `json:"error"`
	Meta    Meta        `json:"meta"`
	Success bool        `json:"success"`
}

func (response GetApiSchemas200JSONResponse) VisitGetApiSchemasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiSchemasRequestObject struct {
	Body *PostApiSchemasJSONRequestBody
}

type PostApiSchemasResponseObject interface {
	VisitPostApiSchemasResponse(w http.ResponseWriter) error
}

type PostApiSchemas200JSONResponse struct {
	Code    int       `json:"code"`
	Data    LogSchema `json:"data"`
	Error   string    `json:"error"`
	Meta    Meta      `json:"meta"`
	Success bool      `json:"success"`
}

func (response PostApiSchemas200JSONResponse) VisitPostApiSchemasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiSchemasSearchRequestObject struct {
	Body *PostApiSchemasSearchJSONRequestBody
}

type PostApiSchemasSearchResponseObject interface {
	VisitPostApiSchemasSearchResponse(w http.ResponseWriter) error
}

type PostApiSchemasSearch200JSONResponse struct {
	Code    int         `json:"code"`
	Data    []LogSchema `json:"data"`
	Error   string      `json:"error"`
	Meta    Meta        `json:"meta"`
	Success bool        `json:"success"`
}

func (response PostApiSchemasSearch200JSONResponse) VisitPostApiSchemasSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiSchemasIdRequestObject struct {
	Id string `json:"id"`
}

type GetApiSchemasIdResponseObject interface {
	VisitGetApiSchemasIdResponse(w http.ResponseWriter) error
}

type GetApiSchemasId200JSONResponse struct {
	Code    int       `json:"code"`
	Data    LogSchema `json:"data"`
	Error   string    `json:"error"`
	Meta    Meta      `json:"meta"`
	Success bool      `json:"success"`
}

func (response GetApiSchemasId200JSONResponse) VisitGetApiSchemasIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutApiSchemasIdRequestObject struct {
	Id   string `json:"id"`
	Body *PutApiSchemasIdJSONRequestBody
}

type PutApiSchemasIdResponseObject interface {
	VisitPutApiSchemasIdResponse(w http.ResponseWriter) error
}

type PutApiSchemasId200JSONResponse struct {
	Code    int       `json:"code"`
	Data    LogSchema `json:"data"`
	Error   string    `json:"error"`
	Meta    Meta      `json:"meta"`
	Success bool      `json:"success"`
}

func (response PutApiSchemasId200JSONResponse) VisitPutApiSchemasIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiSessionRequestObject struct {
}

type GetApiSessionResponseObject interface {
	VisitGetApiSessionResponse(w http.ResponseWriter) error
}

type GetApiSession200JSONResponse struct {
	Code    int     `json:"code"`
	Data    Session `json:"data"`
	Error   string  `json:"error"`
	Meta    Meta    `json:"meta"`
	Success bool    `json:"success"`
}

func (response GetApiSession200JSONResponse) VisitGetApiSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiSessionRequestObject struct {
	Body *PostApiSessionJSONRequestBody
}

type PostApiSessionResponseObject interface {
	VisitPostApiSessionResponse(w http.ResponseWriter) error
}

type PostApiSession200JSONResponse struct {
	Code    int     `json:"code"`
	Data    Session `json:"data"`
	Error   string  `json:"error"`
	Meta    Meta    `json:"meta"`
	Success bool    `json:"success"`
}

func (response PostApiSession200JSONResponse) VisitPostApiSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiUsersRequestObject struct {
}

type GetApiUsersResponseObject interface {
	VisitGetApiUsersResponse(w http.ResponseWriter) error
}

type GetApiUsers200JSONResponse struct {
	Code    int    `json:"code"`
	Data    []User `json:"data"`
	Error   string `json:"error"`
	Meta    Meta   `json:"meta"`
	Success bool   `json:"success"`
}

func (response GetApiUsers200JSONResponse) VisitGetApiUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUsersRequestObject struct {
	Body *PostApiUsersJSONRequestBody
}

type PostApiUsersResponseObject interface {
	VisitPostApiUsersResponse(w http.ResponseWriter) error
}

type PostApiUsers200JSONResponse struct {
	Code    int    `json:"code"`
	Data    User   `json:"data"`
	Error   string `json:"error"`
	Meta    Meta   `json:"meta"`
	Success bool   `json:"success"`
}

func (response PostApiUsers200JSONResponse) VisitPostApiUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiUsersIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteApiUsersIdResponseObject interface {
	VisitDeleteApiUsersIdResponse(w http.ResponseWriter) error
}

type DeleteApiUsersId200JSONResponse struct {
	Code int `json:"code"`

	// Data Deleted User's ID
	Data    int    `json:"data"`
	Error   string `json:"error"`
	Meta    Meta   `json:"meta"`
	Success bool   `json:"success"`
}

func (response DeleteApiUsersId200JSONResponse) VisitDeleteApiUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiUsersIdRequestObject struct {
	Id string `json:"id"`
}

type GetApiUsersIdResponseObject interface {
	VisitGetApiUsersIdResponse(w http.ResponseWriter) error
}

type GetApiUsersId200JSONResponse struct {
	Code    int    `json:"code"`
	Data    User   `json:"data"`
	Error   string `json:"error"`
	Meta    Meta   `json:"meta"`
	Success bool   `json:"success"`
}

func (response GetApiUsersId200JSONResponse) VisitGetApiUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutApiUsersIdRequestObject struct {
	Id   string `json:"id"`
	Body *PutApiUsersIdJSONRequestBody
}

type PutApiUsersIdResponseObject interface {
	VisitPutApiUsersIdResponse(w http.ResponseWriter) error
}

type PutApiUsersId200JSONResponse struct {
	Code    int    `json:"code"`
	Data    User   `json:"data"`
	Error   string `json:"error"`
	Meta    Meta   `json:"meta"`
	Success bool   `json:"success"`
}

func (response PutApiUsersId200JSONResponse) VisitPutApiUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/logs)
	GetApiLogs(ctx context.Context, request GetApiLogsRequestObject) (GetApiLogsResponseObject, error)

	// (POST /api/logs)
	PostApiLogs(ctx context.Context, request PostApiLogsRequestObject) (PostApiLogsResponseObject, error)

	// (GET /api/logs/group/{schema_name}/{hash})
	GetApiLogsGroupSchemaNameHash(ctx context.Context, request GetApiLogsGroupSchemaNameHashRequestObject) (GetApiLogsGroupSchemaNameHashResponseObject, error)

	// (POST /api/logs/search)
	PostApiLogsSearch(ctx context.Context, request PostApiLogsSearchRequestObject) (PostApiLogsSearchResponseObject, error)

	// (GET /api/logs/{id})
	GetApiLogsId(ctx context.Context, request GetApiLogsIdRequestObject) (GetApiLogsIdResponseObject, error)

	// (GET /api/schemas)
	GetApiSchemas(ctx context.Context, request GetApiSchemasRequestObject) (GetApiSchemasResponseObject, error)

	// (POST /api/schemas)
	PostApiSchemas(ctx context.Context, request PostApiSchemasRequestObject) (PostApiSchemasResponseObject, error)

	// (POST /api/schemas/search)
	PostApiSchemasSearch(ctx context.Context, request PostApiSchemasSearchRequestObject) (PostApiSchemasSearchResponseObject, error)

	// (GET /api/schemas/{id})
	GetApiSchemasId(ctx context.Context, request GetApiSchemasIdRequestObject) (GetApiSchemasIdResponseObject, error)

	// (PUT /api/schemas/{id})
	PutApiSchemasId(ctx context.Context, request PutApiSchemasIdRequestObject) (PutApiSchemasIdResponseObject, error)

	// (GET /api/session)
	GetApiSession(ctx context.Context, request GetApiSessionRequestObject) (GetApiSessionResponseObject, error)

	// (POST /api/session)
	PostApiSession(ctx context.Context, request PostApiSessionRequestObject) (PostApiSessionResponseObject, error)

	// (GET /api/users)
	GetApiUsers(ctx context.Context, request GetApiUsersRequestObject) (GetApiUsersResponseObject, error)

	// (POST /api/users)
	PostApiUsers(ctx context.Context, request PostApiUsersRequestObject) (PostApiUsersResponseObject, error)

	// (DELETE /api/users/{id})
	DeleteApiUsersId(ctx context.Context, request DeleteApiUsersIdRequestObject) (DeleteApiUsersIdResponseObject, error)

	// (GET /api/users/{id})
	GetApiUsersId(ctx context.Context, request GetApiUsersIdRequestObject) (GetApiUsersIdResponseObject, error)

	// (PUT /api/users/{id})
	PutApiUsersId(ctx context.Context, request PutApiUsersIdRequestObject) (PutApiUsersIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHttpHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHttpMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiLogs operation middleware
func (sh *strictHandler) GetApiLogs(w http.ResponseWriter, r *http.Request) {
	var request GetApiLogsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiLogs(ctx, request.(GetApiLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiLogsResponseObject); ok {
		if err := validResponse.VisitGetApiLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiLogs operation middleware
func (sh *strictHandler) PostApiLogs(w http.ResponseWriter, r *http.Request) {
	var request PostApiLogsRequestObject

	var body PostApiLogsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiLogs(ctx, request.(PostApiLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiLogsResponseObject); ok {
		if err := validResponse.VisitPostApiLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiLogsGroupSchemaNameHash operation middleware
func (sh *strictHandler) GetApiLogsGroupSchemaNameHash(w http.ResponseWriter, r *http.Request, schemaName string, hash string) {
	var request GetApiLogsGroupSchemaNameHashRequestObject

	request.SchemaName = schemaName
	request.Hash = hash

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiLogsGroupSchemaNameHash(ctx, request.(GetApiLogsGroupSchemaNameHashRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiLogsGroupSchemaNameHash")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiLogsGroupSchemaNameHashResponseObject); ok {
		if err := validResponse.VisitGetApiLogsGroupSchemaNameHashResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiLogsSearch operation middleware
func (sh *strictHandler) PostApiLogsSearch(w http.ResponseWriter, r *http.Request, params PostApiLogsSearchParams) {
	var request PostApiLogsSearchRequestObject

	request.Params = params

	var body PostApiLogsSearchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiLogsSearch(ctx, request.(PostApiLogsSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiLogsSearch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiLogsSearchResponseObject); ok {
		if err := validResponse.VisitPostApiLogsSearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiLogsId operation middleware
func (sh *strictHandler) GetApiLogsId(w http.ResponseWriter, r *http.Request, id string) {
	var request GetApiLogsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiLogsId(ctx, request.(GetApiLogsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiLogsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiLogsIdResponseObject); ok {
		if err := validResponse.VisitGetApiLogsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiSchemas operation middleware
func (sh *strictHandler) GetApiSchemas(w http.ResponseWriter, r *http.Request) {
	var request GetApiSchemasRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiSchemas(ctx, request.(GetApiSchemasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiSchemas")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiSchemasResponseObject); ok {
		if err := validResponse.VisitGetApiSchemasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiSchemas operation middleware
func (sh *strictHandler) PostApiSchemas(w http.ResponseWriter, r *http.Request) {
	var request PostApiSchemasRequestObject

	var body PostApiSchemasJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiSchemas(ctx, request.(PostApiSchemasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiSchemas")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiSchemasResponseObject); ok {
		if err := validResponse.VisitPostApiSchemasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiSchemasSearch operation middleware
func (sh *strictHandler) PostApiSchemasSearch(w http.ResponseWriter, r *http.Request) {
	var request PostApiSchemasSearchRequestObject

	var body PostApiSchemasSearchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiSchemasSearch(ctx, request.(PostApiSchemasSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiSchemasSearch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiSchemasSearchResponseObject); ok {
		if err := validResponse.VisitPostApiSchemasSearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiSchemasId operation middleware
func (sh *strictHandler) GetApiSchemasId(w http.ResponseWriter, r *http.Request, id string) {
	var request GetApiSchemasIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiSchemasId(ctx, request.(GetApiSchemasIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiSchemasId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiSchemasIdResponseObject); ok {
		if err := validResponse.VisitGetApiSchemasIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiSchemasId operation middleware
func (sh *strictHandler) PutApiSchemasId(w http.ResponseWriter, r *http.Request, id string) {
	var request PutApiSchemasIdRequestObject

	request.Id = id

	var body PutApiSchemasIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiSchemasId(ctx, request.(PutApiSchemasIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiSchemasId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutApiSchemasIdResponseObject); ok {
		if err := validResponse.VisitPutApiSchemasIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiSession operation middleware
func (sh *strictHandler) GetApiSession(w http.ResponseWriter, r *http.Request) {
	var request GetApiSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiSession(ctx, request.(GetApiSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiSessionResponseObject); ok {
		if err := validResponse.VisitGetApiSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiSession operation middleware
func (sh *strictHandler) PostApiSession(w http.ResponseWriter, r *http.Request) {
	var request PostApiSessionRequestObject

	var body PostApiSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiSession(ctx, request.(PostApiSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiSessionResponseObject); ok {
		if err := validResponse.VisitPostApiSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiUsers operation middleware
func (sh *strictHandler) GetApiUsers(w http.ResponseWriter, r *http.Request) {
	var request GetApiUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiUsers(ctx, request.(GetApiUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiUsersResponseObject); ok {
		if err := validResponse.VisitGetApiUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiUsers operation middleware
func (sh *strictHandler) PostApiUsers(w http.ResponseWriter, r *http.Request) {
	var request PostApiUsersRequestObject

	var body PostApiUsersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiUsers(ctx, request.(PostApiUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiUsersResponseObject); ok {
		if err := validResponse.VisitPostApiUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiUsersId operation middleware
func (sh *strictHandler) DeleteApiUsersId(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteApiUsersIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiUsersId(ctx, request.(DeleteApiUsersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiUsersId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApiUsersIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiUsersIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiUsersId operation middleware
func (sh *strictHandler) GetApiUsersId(w http.ResponseWriter, r *http.Request, id string) {
	var request GetApiUsersIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiUsersId(ctx, request.(GetApiUsersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiUsersId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiUsersIdResponseObject); ok {
		if err := validResponse.VisitGetApiUsersIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiUsersId operation middleware
func (sh *strictHandler) PutApiUsersId(w http.ResponseWriter, r *http.Request, id string) {
	var request PutApiUsersIdRequestObject

	request.Id = id

	var body PutApiUsersIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiUsersId(ctx, request.(PutApiUsersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiUsersId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutApiUsersIdResponseObject); ok {
		if err := validResponse.VisitPutApiUsersIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaUW/bNhD+K8ZtwF40y23f9JY1SWcg6YpkxR6CIKCli8xOIlWSamoY+u8DKcqSZdpW",
	"Ym+W1rwpFo/Hu++7705SlhDyNOMMmZIQLEGGc0yJuXwvMEKmKEnMn5ngGQpF0fyFKaGJvlCLDCEAqQRl",
	"MRQeZETKJy4ix83CA4FfcyowguDO7tGwuPcqCz77gqHS213x+Aq/ofGFLE+14Z+ChAgenOMsj8GDKXvk",
	"4MFfRDDw4EIILsCDS6JI0tizPuIVj28wtGdcjysUSBRGD0Q5g4sFz7OHOZFz523ajJoyhTEK/XtSRcAZ",
	"/vEIwd0Sfhb4CAH85Nf5923y/VXMxX3hwdccxaKxb52bcv3DNq/2NiMpOk+r8LvajxKNwC5d37E62BbQ",
	"bs3SzQRHKENBM0U5cx7qkWISmZVUYWoudqWqdHOpjUxI5XZECLLYBcjWnAhUmvOcPSi6tqRhrKhKsGvi",
	"zFrrcBXdzpzdIhHh/PmZ23GsDWfXqBzYhDxnyh1zRmLcfke6brXSYXbwrI/KzJWIJqQbR9xO5m6grOHh",
	"9I5S2gyve1b8b2QdHJhlrp0/SxTPEdJnc3eH8tY3HyIao3Srm+BlCruplI7nRlsYleqYHlMUthg29N+e",
	"YFvybuzxqjZwjekMtdKfRSnVyn+7kApTh+RrMcQwF1QtDLvK1M+Vyt6smp5eP0MizI7WXq+AQpvjd4WC",
	"keSch5vFCJeURSOeq1HKBY7ITF/KDEMDo25OpriYIqFOfOG1zK85ZwmP5ejs0xQ8SGiITGJNdzjLSDjH",
	"0dvxBDzIRWKPFvj+09PTmJi7Yy5i35pK/2r6/uLj7cWvb8eT8VylSaNEVu7Ag28oSrbDm/FEr+EZMpJR",
	"CODdeDJ+Z9BRcxOyTzLqG7tgCTEaCmkmEx3FNIIAPqA6y+hVubVGHaX6jUeLKnzU6sLyJDGkkBnXR9U3",
	"304ma2uWQLIsoaHZ2v8iy3qUW1pKyKMt2hSRUuY6tZJ6KnA0EjRDhatoUiulu7Y2cqtJmIchyqZazjhP",
	"kLCNOqlWemV01QFsSNbrZqEURZPrpoQty+/uTZlmXDqA+8RlB+T2odIxuUXxX8PfGfXToWxhrVC2oL8M",
	"5cKra9U3E6u/bExuhb/UA2zRoYw/aOOyH38kKf6u516tCIKkqFBI45pq+dAqUSl70JoT64iVyNFrALkh",
	"087d5qXb7tvcv6rPkXlp3LS06DBeynrK3SdJdiB2E698CFlxxU6Z+ynWsktoShW8kFSDFcYhM9NSstUX",
	"TcyHMXNJoy7aOI06SaEZeAcrXcPpnC06HMaDxluwHSy4tauG2W3sC5o+1rRr5D32rLsfvANVvcpv78bd",
	"GvjTAV1Buw74y4BuFW3XycISYDVc/Ks0sF563OL7KAetp6GDHn3bLOnQ5S1DXht9PzTjyC9Ccpc05KfE",
	"/bXhDIM8KympPxXsUhG7ajj1Xp24D6Og673Y0UfBvQgdUpnNz+g9q81hAr2qv1waWd5ZfZ/NmgE+oZmv",
	"hb2cxo4xs++pyH2oHVKPZWL7VYgV2IOtwtU4HWGCCjeBPTe/V9D+ECP1+jfeMgHRSMf/ixxNz+uvzA3b",
	"/8eLfm+vIv/wz1Snr/jmJ8ZW4R/3ceo0gL+2iD5P5Oaf0khc8sBif46PJE8UFPfFPwEAAP//FUh+kpYq",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
