openapi: 3.0.3
info:
  title: Moonlogs
  description: Moonlogs API
  termsOfService: ''
  contact:
    email: ''
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
externalDocs:
  description: Find out more about spec
  url: ''
servers: []
tags:
  - name: Default
    description: ''
paths:
  /api/schemas:
    get:
      summary: ''
      description: ''
      operationId: ''
      tags: []
      parameters: []
      requestBody: &ref_0 {}
      responses:
        '200':
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LogSchema'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - meta
                  - code
                  - error
                  - data
      security:
        - http1: []
    post:
      summary: ''
      description: ''
      operationId: ''
      tags: &ref_1 []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogSchema'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/LogSchema'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - error
                  - meta
                  - code
                  - data
      security:
        - http1: []
  /api/schemas/{id}:
    get:
      description: ''
      operationId: ''
      tags: []
      parameters:
        - in: path
          name: id
          description: ''
          schema: &ref_2
            type: string
          required: true
      requestBody: *ref_0
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/LogSchema'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - code
                  - error
                  - data
                  - meta
      security:
        - http1: []
    put:
      summary: ''
      description: ''
      operationId: ''
      tags: *ref_1
      parameters:
        - in: path
          name: id
          description: ''
          schema: *ref_2
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogSchema'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/LogSchema'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - code
                  - error
                  - data
                  - meta
      security:
        - http1: []
  /api/schemas/search:
    post:
      description: ''
      operationId: ''
      tags: []
      parameters: &ref_3 []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogSchemaSearch'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LogSchema'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - error
                  - code
                  - data
                  - meta
      security:
        - http1: []
  /api/logs:
    post:
      description: ''
      operationId: ''
      tags: &ref_4 []
      parameters: *ref_3
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogRecord'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/LogRecord'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - data
                  - error
                  - code
                  - meta
      security:
        - http1: []
    get:
      description: ''
      operationId: ''
      tags: *ref_4
      parameters: *ref_3
      requestBody: {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LogRecord'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - code
                  - error
                  - data
                  - meta
      security:
        - http1: []
  /api/logs/{id}:
    get:
      description: ''
      operationId: ''
      tags: []
      parameters:
        - in: path
          name: id
          description: ''
          schema: &ref_5
            type: string
          required: true
      requestBody: &ref_6 {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/LogRecord'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - data
                  - meta
                  - error
                  - code
      security:
        - http1: []
  /api/logs/group/{schema_name}/{hash}:
    get:
      description: ''
      operationId: ''
      tags: []
      parameters:
        - in: path
          name: schema_name
          description: ''
          schema: *ref_5
          required: true
        - in: path
          name: hash
          description: ''
          schema: *ref_5
          required: true
      requestBody: *ref_6
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LogRecord'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - data
                  - meta
                  - code
                  - error
      security:
        - http1: []
  /api/logs/search:
    post:
      description: ''
      operationId: ''
      tags: []
      parameters:
        - in: query
          name: page
          description: ''
          schema: &ref_7
            type: string
        - in: query
          name: limit
          description: ''
          schema: *ref_7
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogRecord'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LogRecord'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - meta
                  - error
                  - data
                  - code
      security:
        - http1: []
  /api/users:
    get:
      description: ''
      operationId: ''
      tags: &ref_8 []
      parameters: &ref_9 []
      requestBody: &ref_10 {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - error
                  - meta
                  - code
                  - data
      security:
        - http1: []
    post:
      description: ''
      operationId: ''
      tags: *ref_8
      parameters: *ref_9
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - meta
                  - data
                  - error
                  - code
  /api/users/{id}:
    get:
      description: ''
      operationId: ''
      tags: &ref_11 []
      parameters:
        - in: path
          name: id
          description: ''
          schema: *ref_5
          required: true
      requestBody: *ref_10
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - code
                  - meta
                  - data
                  - error
      security:
        - http1: []
    delete:
      description: ''
      operationId: ''
      tags: *ref_11
      parameters:
        - in: path
          name: id
          description: ''
          schema: &ref_12
            type: string
          required: true
      requestBody: *ref_10
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    type: integer
                    description: Deleted User's ID
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - data
                  - meta
                  - code
                  - error
      security:
        - http1: []
    put:
      description: ''
      operationId: ''
      tags: *ref_11
      parameters:
        - in: path
          name: id
          description: ''
          schema: *ref_12
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - meta
                  - data
                  - error
                  - code
      security:
        - http1: []
  /api/session:
    get:
      description: ''
      operationId: ''
      tags: &ref_13 []
      parameters: &ref_14 []
      requestBody: {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/Session'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - meta
                  - data
                  - error
                  - code
      security:
        - http1: []
    post:
      description: ''
      operationId: ''
      tags: *ref_13
      parameters: *ref_14
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/Session'
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - success
                  - meta
                  - data
                  - error
                  - code
components:
  schemas:
    LogSchema:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        name:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/SchemaField'
        retention_time:
          type: integer
      required:
        - id
        - title
        - name
        - fields
    SchemaField:
      type: object
      properties:
        title:
          type: string
        name:
          type: string
      required:
        - title
        - name
    LogRecord:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        schema_name:
          type: string
        schema_id:
          type: integer
        query:
          type: object
          properties: {}
        created_at:
          type: string
        group_hash:
          type: string
        level:
          oneOf:
            - $ref: '#/components/schemas/LogLevel'
      required:
        - id
        - text
        - schema_name
        - query
    LogLevel:
      type: string
      enum:
        - Trace
        - Debug
        - Info
        - Warn
        - Error
        - Fatal
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string
        password_digest:
          type: string
        role:
          oneOf:
            - $ref: '#/components/schemas/UserRole'
        token:
          type: string
      required:
        - id
        - name
        - email
        - password
        - role
    UserRole:
      type: string
      enum:
        - Member
        - Admin
        - System
    LogSchemaSearch:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
    Meta:
      type: object
      properties:
        page:
          type: integer
        count:
          type: integer
        pages:
          type: integer
      required:
        - page
        - count
        - pages
    Credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    Session:
      type: object
      properties:
        token:
          type: string
      required:
        - token
  securitySchemes:
    http1:
      type: http
      scheme: bearer
