name: goreleaser

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest

    outputs:
      web-build: ${{ steps.build.outputs.web-build }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --prefix web

      - name: Build Web Part
        run: npm run build --prefix web

      - name: Archive Web Build
        id: build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: web/build
  goreleaser:
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Download Web Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: web/build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURYPUSHTOKEN }}
