name: Lint Steiger FSD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix web

      - name: Run linting
        run: npm run steiger --prefix web
