/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        eigengrau: "#1b1b1f",
        "raisin-black": "#202127",
        "squid-ink": "#32363f",
        "shadow-gray": "#3c3f44",
        "slate-gray": "#65758529",
      },
      maxWidth: {
        5: "5rem",
      },
      borderWidth: {
        1: "1px",
        10: "10px",
        12: "12px",
      },
    },
  },
  safelist: [
    "rounded-tl-lg",
    "rounded-bl-lg",
    "green-500",
    "blue-500",
    "gray-500",
    "yellow-500",
    "red-500",
    "pink-500",
    "purple-500",
    "lime-500",
    "cyan-500",
    "orange-500",
    "bg-blue-500",
    "bg-gray-500",
    "bg-yellow-500",
    "bg-red-500",
    "bg-pink-500",
    "bg-purple-500",
    "bg-lime-500",
    "bg-cyan-500",
    "bg-orange-500",
    "border-l-blue-500",
    "border-l-gray-500",
    "border-l-yellow-500",
    "border-l-red-500",
    "border-l-pink-500",
    "border-l-purple-500",
    "border-l-lime-500",
    "border-l-cyan-500",
    "border-l-orange-500",
    "border-blue-500",
    "border-gray-500",
    "border-yellow-500",
    "border-red-500",
    "border-pink-500",
    "border-purple-500",
    "border-lime-500",
    "border-cyan-500",
    "border-orange-500",
    "before:border-blue-500",
    "before:border-gray-500",
    "before:border-yellow-500",
    "before:border-red-500",
    "before:border-pink-500",
    "before:border-purple-500",
    "before:border-lime-500",
    "before:border-cyan-500",
    "before:border-orange-500",
    "before:rounded-tl-lg",
    "before:rounded-bl-lg",
    "before:rounded-tl-xl",
    "before:rounded-bl-xl",
  ],
  darkMode: "class",
  plugins: [require("tailwind-scrollbar")],
};
