// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LogRecord is the predicate function for logrecord builders.
type LogRecord func(*sql.Selector)

// LogSchema is the predicate function for logschema builders.
type LogSchema func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
